version: 1

defaults:
  output:
    owner: amanbolat
    repoSuffix: "-with-stars"
    branch: main
    path: README.md
  source:
    branch: main
    path: README.md
  parser: default
  parserOptions:
    headingDepths: [2, 3]
  table:
    columns: [stars, name, description]
    sort: stars_desc

list:
  id: awesome-go
  source:
    owner: avelino
    repo: awesome-go
    branch: master
