version: 1

defaults:
  output:
    owner: amanbolat
    repoSuffix: "-with-stars"
    branch: main
    path: README.md
  source:
    branch: main
    path: README.md
  parser: default
  parserOptions:
    headingDepths: [2, 3]
  table:
    columns: [stars, name, description]
    sort: stars_desc

lists:
  - id: awesome-go
    source:
      owner: avelino
      repo: awesome-go
      branch: master

  - id: awesome-rust
    source:
      owner: rust-unofficial
      repo: awesome-rust

  - id: awesome-zig
    source:
      owner: zigcc
      repo: awesome-zig

  - id: awesome-postgres
    source:
      owner: dhamaniasad
      repo: awesome-postgres
