version: 1

list:
  id: awesome-rust
  header: |
    # Awesome Rust

    This repository is a clone of [Awesome Rust](https://github.com/rust-unofficial/awesome-rust) but with stars.
    All repositories are sorted by star count. Stars are updated every day automatically.
  toc: true
  source:
    owner: rust-unofficial
    repo: awesome-rust
    branch: main
  output:
    owner: amanbolat
  parser: awesome-rust
